name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs
          installer-parallel: true

      - name: Cache poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install
          sudo apt-get update
          sudo apt-get install -y imagemagick tesseract-ocr ghostscript libdmtx0b allure
          export release_name=gs952
          export archive_name=ghostpcl-9.52-linux-x86_64
          wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/${release_name}/${archive_name}.tgz
          tar -xvzf ${archive_name}.tgz
          chmod +x ${archive_name}/gpcl6*
          cp ${archive_name}/gpcl6* ${archive_name}/pcl6
          sudo cp ${archive_name}/* /usr/bin
          sudo cp policy.xml /etc/ImageMagick-6/
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        run: |
          poetry run invoke tests